import "./globals.css";
import ContextProvider from "@/components/context-provider";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ContextProvider>
                    <Header />

                    <main>{children}</main>

                    <Footer />

                    {/* <div className="help-chat-pop-up" ref={helpPopUp}>
                    <h5>Do you need help?</h5>
                    <div>
                        <button onClick={hideHelp}>No, please hide</button>
                        <button onClick={navigateToHelp}>Yes, please open help chat</button>
                    </div>
             </div> */}
                </ContextProvider>
            </body>
        </html>
    );
}
