import './globals.css';
import ContextProvider from '@/components/context-provider';
import Header from '@/components/header/header';
import Footer from '@/components/footer/footer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

    // const hideHelp = () => {
    //     localStorage.setItem('hideHelpPopUp', new Date().getTime());
    //     helpPopUp.current.style.display = 'none';
    // };

    // const navigateToHelp = () => {
    //     navigate('/help-chat');
    //     helpPopUp.current.style.display = 'none';
    // };

    // useEffect(() => {
    //     if ((new Date().getTime() - localStorage.getItem('hideHelpPopUp')) > 43_200_200) {
    //         helpPopUp.current.style.display = 'block';
    //     } else {
    //         helpPopUp.current.style.display = 'none';
    //     }
    //     !localDataBank.user &&
    //     (helpPopUp.current.style.display = 'none');
    // }, []);

  return (
    <html lang="en">
      <body>
        <ContextProvider>

            <Header/>

            <main>
              {children}
            </main>

            <Footer/>

            {/* <div className="help-chat-pop-up" ref={helpPopUp}>
                    <h5>Do you need help?</h5>
                    <div>
                        <button onClick={hideHelp}>No, please hide</button>
                        <button onClick={navigateToHelp}>Yes, please open help chat</button>
                    </div>
            </div> */}

        </ContextProvider>
      </body>
    </html>
  )
}